export const GAME_LIST_REQUEST = "GAME_LIST_REQUEST";
export const GAME_LIST_SUCCESS = "GAME_LIST_SUCCESS";
export const GAME_LIST_FAIL = "GAME_LIST_FAIL";

export const PAYMENT_UPDATE_REQUEST = "PAYMENT_UPDATE_REQUEST";
export const PAYMENT_UPDATE_SUCCESS = "PAYMENT_UPDATE_SUCCESS";
export const PAYMENT_UPDATE_FAIL = "PAYMENT_UPDATE_FAIL";